#steps:
 #     - name: gcr.io/searce-msp-gcp/firebase
  #      args:
   #     - '-c'
    #    - |
     #     if [[ "$COMMIT_MESSAGE" == *"group1"* ]]; then
      #      echo "Triggering build for specific commit message."
       #     firebase deploy --only functions
        #    firebase deploy --only hosting
         # else
          #  echo "Skipping build for commit message: $COMMIT_MESSAGE"
          #fi


#
steps:
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    if git log -1 --pretty=%B | grep -q "group1"; then
      firebase deploy --only functions
      # Deploy Firebase hosting
      firebase deploy --only hosting
      exit 0
    else
      exit 1
    fi


