steps:
      - name: gcr.io/searce-msp-gcp/firebase
        args:
        - '-c'
        - |
          if [[ "$COMMIT_MESSAGE" == *"group1"* ]]; then
            echo "Triggering build for specific commit message."
            firebase deploy --only functions
            firebase deploy --only hosting
          else
            echo "Skipping build for commit message: $COMMIT_MESSAGE"
          fi

